---
- name: Install Docker via official script
  ansible.builtin.shell:
    cmd: curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker

- name: Add {{ username }} to docker group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true

- name: Install lazydocker
  ansible.builtin.shell:
    cmd: curl -fsSL https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  become: true
  become_user: "{{ username }}"
  args:
    creates: "/home/{{ username }}/.local/bin/lazydocker"
