---
- name: Create .ssh directory for {{ username }}
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"

- name: Deploy authorized_keys for {{ username }}
  ansible.builtin.copy:
    src: authorized_keys
    dest: "/home/{{ username }}/.ssh/authorized_keys"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"
