---
- name: Install pipx
  ansible.builtin.apt:
    name:
      - pipx
      - python3-full
    state: present
    update_cache: true

- name: Install Ansible via pipx for {{ control_user }}
  ansible.builtin.command:
    cmd: pipx install ansible --include-deps
    creates: "/home/{{ control_user }}/.local/bin/ansible"
  become: true
  become_user: "{{ control_user }}"
