---
- name: Install YABS benchmark script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/masonr/yet-another-bench-script/master/yabs.sh
    dest: /usr/local/bin/yabs
    mode: "0755"
