---
- name: Set up VPS
  hosts: all
  become: true
  roles:
    - wait_for_apt
    - create_user
    - setup_ssh
    - create_automation_user
    - harden_ssh
    - setup_ufw
    - setup_fail2ban
    - set_hostname
    - set_timezone
    - setup_swap
    - apt_packages
    - install_yabs
    - install_awscli
    - install_bun
    - install_just
    - install_node
    - install_claude
    - install_starship
    - setup_git
    - setup_dotfiles
    - setup_tailscale
    - setup_motd
    - lockdown_ufw
