all:
  hosts:
    # Add bootstrapped VPS here with Tailscale IP + automation user.
    #
    # Example:
    # my-vps:
    #   ansible_host: 100.x.x.x
    ndt-2:
      ansible_host: 100.79.252.58
    p-sea-1:
      ansible_host: 100.111.35.50
  vars:
    ansible_user: automation
    ansible_ssh_private_key_file: ~/.ssh/id_automation
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
